import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar";
import HeaderBar from "@/components/headerbar";
import { useRouter } from "next/navigation";

export const metadata: Metadata = {
  title: "TaskyApp",
  description: "Generated by create next app",
};

export default function BoardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="flex overflow-hidden h-screen min-h-[100dvh] py-2">
        <Sidebar />
      {children}
    </main>
  );
}
