import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar";
import HeaderBar from "@/components/headerbar";
import { useRouter } from "next/navigation";

export const metadata: Metadata = {
  title: "TaskyApp",
  description: "Generated by create next app",
};

export default function BoardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex overflow-hidden min-h-[100dvh] h-full py-2">
      <aside className="">
        <Sidebar />
      </aside>
      {children}
    </main>
  );
}
