import type { Metadata } from "next";
import HeaderBar from "@/components/headerbar";
import { checkUser } from "@/app/(main)/account/_action/account-action";
import { Toaster } from "@/components/ui/toaster"
import ModalProvider from "@/providers/modal-provider";
import SidebarMenuAccount from "../_components/sidebar-menu-account";
export const metadata: Metadata = {
  title: "TaskyApp",
  description: "Generated by create next app",
};

export default async function BoardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await checkUser();

  if (!user) {
    return null;
  }
  return (
      <main className="overflow-hidden h-screen min-h-[100dvh]">
        <ModalProvider>
          <HeaderBar />
          <div className="flex">
            <SidebarMenuAccount />
            <aside className="w-full border-l-[1px] rounded-l-2xl h-screen CardStyle border-t-[1px] border-muted-foreground/20 overflow-scroll">
              {children}
            </aside>
          </div>
          <Toaster />
        </ModalProvider>
    </main>
  );
}
