import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BoardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <section className="flex">
        <Sidebar />
        <main>
        {children}
      </main>
      </section>
  );
}
