import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
      <section className="flex">
        {children}
      </section>
  );
}
export default layout